---
  - name: Create NFS exports
    file:
      path: /shares/{{ item.name }}
      state: directory
    loop: "{{ nfs_export_list }}"

  - name: Fix ownership and permissions on NFS exports
    file:
      path: "/shares"
      state: directory
      recurse: yes
      owner: root
      group: root
      mode: u=rwX,g=rX,o=rX

  - name: Setup SELinux context for NFS exports
    sefcontext:
      target: '/shares(/.*)?'
      setype: public_content_rw_t
      state: present
    register: selinuxchanged

  - name: Apply new SELinux context to NFS exports
    command: restorecon -Rv /shares
    when: selinuxchanged.changed

  - name: Generate exports file
    template:
      src: exports.j2
      dest: /etc/exports
    register: exportschanged

  - name: Ensure NFS server is started and enabled
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - rpcbind
      - nfs-server

  - name: Activate NFS exports
    command: exportfs -r
    when: exportschanged.changed
    