---
  - name: Fix ownership and permissions on NFS exports
    file:
      path: "/shares"
      state: directory
      recurse: yes
      owner: root
      group: root
      mode: u=rwX,g=rX,o=rX

  - name: Setup SELinux context for NFS exports
    sefcontext:
      target: '/shares(/.*)?'
      setype: public_content_rw_t
      state: present
    register: selinuxchanged

  - name: Apply new SELinux context to NFS exports
    command: restorecon -Rv /shares
    when: selinuxchanged.changed
    