require 'yaml'

# Study environment target OS
# Set to 'rhel7' or 'rhel8'
environment_os = 'rhel8'

# Common variables
common = YAML.load_file('../common/Vagrantfile-config.yml')

# Study environment variables
environment = YAML.load_file('environment.yml')

# Vagrant API Version
vagrant_api_version = common['vagrant_api_version']

# Default services box configuration
services_box = common[environment_os + '_services_box']
services_box_version = common[environment_os + '_services_box_version']

# Default study box configuration
study_box = common[environment_os + '_study_box']
study_box_version = common[environment_os + '_study_box_version']

# ISO
iso_filename = common[environment_os + '_iso_name']

# Services box RAM configuration (in MB)
services_box_ram = environment['services_box_ram']

# How many study boxes to provision
study_box_num = environment['study_box_num']

# Study box RAM configuration (in MB)
study_box_ram = environment['study_box_ram']

# Study box additional hard drive configuration
# Array of integer sizes (in GB)
study_box_drives = environment['study_box_drives']

# Add SATA controller
eval File.read('../common/Vagrantfile.add_controller')

Vagrant.configure(vagrant_api_version) do |config|
  # Setup sync folders
  eval File.read('../common/Vagrantfile.sync_folders')

  # Services box configuration
  eval File.read('../common/Vagrantfile.services')

  # Study box configuration
  eval File.read('../common/Vagrantfile.study')
end
