Vagrant.configure("2") do |config|

  # Services box configuration
  config.vm.define "services" do |domain|
    domain.vm.box = "dean1012/rhel8-services"
    domain.vm.box_version = "1.0"
    domain.vm.synced_folder ".", "/home/vagrant/sync", type: "rsync", rsync__exclude: ".git/"
    domain.vm.network :private_network, :ip => '172.25.250.10'

    domain.vm.provider "libvirt" do |v|
      v.disk_bus = 'sata'
      v.memory = 1024
    end

    domain.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
    
    # Run machine specific pre-configuration script, if any
    domain.vm.provision "shell", path: "services/setup.sh"
    
    # Kick off Ansible
    domain.vm.provision "shell",
    inline: "cd ~vagrant/sync/services && ansible-playbook site.yml"
  end

  # Server1 box configuration
  config.vm.define "server1", primary: true do |domain|
    domain.vm.box = "dean1012/rhel8-base"
    domain.vm.box_version = "1.0"
    domain.vm.synced_folder ".", "/home/vagrant/sync", type: "rsync", rsync__exclude: [".git/", "iso"]
    domain.vm.network :private_network, :ip => '172.25.250.11'

    domain.vm.provider "libvirt" do |v|
      v.disk_bus = 'sata'
      v.memory = 1024
    end

    domain.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
    
    # Kick off Ansible
    domain.vm.provision "shell",
    inline: "cd ~vagrant/sync/server1 && ansible-playbook site.yml"

    # Output instructions to the learner
    domain.vm.post_up_message = "To access server1, please ssh to '172.25.250.11' with username 'student' and password 'student'."
  end

  # Server2 box configuration
  config.vm.define "server2" do |domain|
    domain.vm.box = "dean1012/rhel8-base"
    domain.vm.box_version = "1.0"
    domain.vm.synced_folder ".", "/home/vagrant/sync", type: "rsync", rsync__exclude: [".git/", "iso"]
    domain.vm.network :private_network, :ip => '172.25.250.12'

    domain.vm.provider "libvirt" do |v|
      v.disk_bus = 'sata'
      v.memory = 1024
    end

    domain.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
    
    # Kick off Ansible
    domain.vm.provision "shell",
    inline: "cd ~vagrant/sync/server2 && ansible-playbook site.yml"

    # Output instructions to the learner
    domain.vm.post_up_message = "To access server2, please ssh to '172.25.250.12' with username 'student' and password 'student'."
  end

end
