---
  - name: Restart NetworkManager
    service:
      name: NetworkManager
      state: restarted

  - name: Restart Chronyd
    service:
      name: chronyd
      state: restarted
      
  - name: Clean package manager cache
    changed_when: false
    command: yum clean all
    args:
      warn: false
