Vagrant.configure("2") do |config|

  # All boxes use these settings
  config.vm.box = "centos/7"
  config.vm.box_version = "1505.01"

  # Services box configuration
  config.vm.define "services" do |services|
    services.vm.network :private_network, :ip => '172.25.250.10'

    config.vm.provider "virtualbox" do |v|
      v.name = 'services'
      v.customize ["modifyvm", :id, "--memory", "1024"]

      # Add a secondary drive (5 GB)
      file_to_disk = "vdb.vmdk"
      unless File.exist?(file_to_disk)
        v.customize [ "createmedium", "disk", "--filename", "vdb.vmdk", "--format", "vmdk", "--size", 1024 * 5 ]
      end
      v.customize [ "storageattach", "services" , "--storagectl", "IDE Controller", "--port", "1", "--device", "0", "--type", "hdd", "--medium", file_to_disk]
    end

    config.vm.provider "libvirt" do |v|
      v.memory = 1024
      
      # Add a secondary drive (5 GB)
      v.storage :file, :size => '5G'
    end

    # Install latest Ansible
    config.vm.provision "shell",
    inline: "yum -y install python wget && yum -y update curl && curl https://bootstrap.pypa.io/get-pip.py | python && pip install ansible"
    
    # Run machine specific pre-configuration script, if any
    config.vm.provision "shell", path: "services/setup.sh"

    # Disable internet access then kick off Ansible
    config.vm.provision "shell",
    inline: "ip route del 0/0 && cd ~vagrant/sync/services && ansible-playbook site.yml"
  end

  # Output instructions to the learner
  config.vm.post_up_message = "Please ssh to '172.25.250.11' with username 'student' and password 'student'."

end
