Vagrant.configure("2") do |config|

  # All boxes use these settings
  config.vm.box = "dean1012/centos-7.0"
  config.vm.box_version = "1.0"
  config.vm.synced_folder ".", "/home/vagrant/sync", type: "rsync", rsync__exclude: ".git/"

  # Services box configuration
  config.vm.define "services" do |domain|
    domain.vm.network :private_network, :ip => '172.25.250.10'

    domain.vm.provider "libvirt" do |v|
      v.disk_bus = 'sata'
      v.memory = 1024
    end

    domain.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    # Install latest Ansible
    domain.vm.provision "shell",
    inline: "yum -y install python && yum -y update curl && curl https://bootstrap.pypa.io/get-pip.py | python && pip install ansible"
    
    # Run machine specific pre-configuration script, if any
    domain.vm.provision "shell", path: "services/setup.sh"

    # Disable internet access
    domain.vm.provision "shell",
    inline: "ip route del 0/0",
    run: "always"
    
    # Kick off Ansible
    domain.vm.provision "shell",
    inline: "cd ~vagrant/sync/services && ansible-playbook site.yml",
    run: "always"
  end

  # Server1 box configuration
  config.vm.define "server1", primary: true do |domain|
    domain.vm.network :private_network, :ip => '172.25.250.11'

    domain.vm.provider "libvirt" do |v|
      v.disk_bus = 'sata'
      v.memory = 1024
      
      # Add a secondary drive (5 GB)
      v.storage :file, :size => '5G', :bus => 'sata'
    end

    domain.vm.provider "virtualbox" do |v|
      v.memory = 1024

      # Create a secondary drive (5 GB) if it doesn't yet exist
      unless File.exist?("./server1-sdb.vdi")
        v.customize ['createhd', '--filename', "./server1-sdb.vdi", '--size', 5 * 1024]
      end

      # Attach the secondary drive to the server
      v.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "./server1-sdb.vdi"]
    end

    # Install latest Ansible
    domain.vm.provision "shell",
    inline: "yum -y install python && yum -y update curl && curl https://bootstrap.pypa.io/get-pip.py | python && pip install ansible"

    # Disable internet access
    domain.vm.provision "shell",
    inline: "ip route del 0/0",
    run: "always"
    
    # Kick off Ansible
    domain.vm.provision "shell",
    inline: "cd ~vagrant/sync/server1 && ansible-playbook site.yml",
    run: "always"

    # Output instructions to the learner
    domain.vm.post_up_message = "To access server1, please ssh to '172.25.250.11' with username 'student' and password 'student'."
  end

  # Server2 box configuration
  config.vm.define "server2" do |domain|
    domain.vm.network :private_network, :ip => '172.25.250.12'

    domain.vm.provider "libvirt" do |v|
      v.disk_bus = 'sata'
      v.memory = 1024
      
      # Add a secondary drive (5 GB)
      v.storage :file, :size => '5G', :bus => 'sata'
    end

    domain.vm.provider "virtualbox" do |v|
      v.memory = 1024

      # Create a secondary drive (5 GB) if it doesn't yet exist
      unless File.exist?("./server2-sdb.vdi")
        v.customize ['createhd', '--filename', "./server2-sdb.vdi", '--size', 5 * 1024]
      end

      # Attach the secondary drive to the server
      v.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "./server2-sdb.vdi"]
    end

    # Install latest Ansible
    domain.vm.provision "shell",
    inline: "yum -y install python && yum -y update curl && curl https://bootstrap.pypa.io/get-pip.py | python && pip install ansible"

    # Disable internet access
    domain.vm.provision "shell",
    inline: "ip route del 0/0",
    run: "always"
    
    # Kick off Ansible
    domain.vm.provision "shell",
    inline: "cd ~vagrant/sync/server2 && ansible-playbook site.yml",
    run: "always"

    # Output instructions to the learner
    domain.vm.post_up_message = "To access server2, please ssh to '172.25.250.12' with username 'student' and password 'student'."
  end

end

