# Vagrant API version
vagrant_api_version='2'

# Study environment target OS
environment_os='RHEL8'

# Autodetect box configuration and ISO based on environment target OS
if environment_os == 'RHEL7'
  # Default services box configuration
  services_box='dean1012/rhel7-services'
  services_box_version='1.0'

  # Default study box configuration
  study_box = "dean1012/rhel7-base"
  study_box_version='1.0'

  # ISO
  iso_filename='rhel-server-7.0-x86_64-dvd.iso'
elsif environment_os == 'RHEL8'
  # Default services box configuration
  services_box='dean1012/rhel8-services'
  services_box_version='1.0'

  # Default study box configuration
  study_box = "dean1012/rhel8-base"
  study_box_version='1.0'

  # ISO
  iso_filename='rhel-8.0-x86_64-dvd.iso'
end

# Services box RAM configuration
services_box_ram = 1024

# How many study boxes to provision
study_box_num = 1

# Study box RAM configuration
study_box_ram = 1024

# Study box additional hard drive configuration
# Array of integer sizes (in GB)
study_box_drives = [
  5
]

# Add SATA controller
eval File.read('../common/Vagrantfile.add_controller')

Vagrant.configure(vagrant_api_version) do |config|
  # Disable default sync folder
  config.vm.synced_folder '.',
                          '/vagrant',
                          disabled: true

  # Setup common sync folders
  config.vm.synced_folder '.',
                          '/home/vagrant/sync',
                          type: 'rsync',
                          rsync__verbose: true,
                          rsync__auto: false,
                          rsync__exclude: [
                            'Vagrantfile*'
                          ]
  config.vm.synced_folder '../common',
                          '/home/vagrant/common',
                          type: 'rsync',
                          rsync__verbose: true,
                          rsync__auto: false,
                          rsync__exclude: [
                            'iso', 
                            'Vagrantfile*',
                            '*.sh'
                          ]

  # Services box configuration
  eval File.read('Vagrantfile.services')

  # Study box configuration
  eval File.read('Vagrantfile.study')
end
