---
- name: Setup services server
  hosts: localhost
  vars:
    install_packages:
      - nfs-utils
      - rpcbind
      - python3-policycoreutils
    firewall_services:
      - nfs
      - mountd
      - rpc-bind
    nfs_export_list:
      - name: share1
        permissions: ro
      - name: share2
        permissions: rw
  roles:
    - common_base
    - ex200
  tasks:
    - name: Mark provisioning as complete
      copy:
        content: complete
        dest: /var/www/html/complete.txt
        mode: 0644
        setype: httpd_sys_content_t
