---
- name: Setup services server
  hosts: localhost
  vars:
    firewall_services:
      - http
      - dns
      - ntp
  roles:
    - common_base
  tasks:
    - name: Mark provisioning as complete
      copy:
        content: complete
        dest: /var/www/html/complete.txt
        mode: 0644
        setype: httpd_sys_content_t
