---
- name: Setup services server
  hosts: localhost
  vars:
    firewall_services:
      - http
      - dns
      - ntp
  roles:
    - common_base
  tasks:
  - name: Ensure Apache is started and enabled
    service:
      name: httpd
      enabled: yes
      state: started

  - name: Ensure dnsmasq is started and enabled
    service:
      name: dnsmasq
      enabled: yes
      state: started

  # this task should always run last
  - name: Mark provisioning as complete
    copy:
      content: complete
      dest: /var/www/html/complete.txt
      mode: 0644
      setype: httpd_sys_content_t
