---
- hosts: localhost
  vars:
    hostname: services.example.com
    firewall_services:
      - ssh
      - http
      - dns
      - ntp
  roles:
    - base
  tasks:
  - name: Ensure Apache is started and enabled
    service:
      name: httpd
      enabled: yes
      state: started

  - name: Ensure dnsmasq is started and enabled
    service:
      name: dnsmasq
      enabled: yes
      state: started

