---
  - name: Restart NetworkManager
    service:
      name: NetworkManager
      state: restarted

  - name: Clean dnf cache
    changed_when: false
    command: dnf clean all
    args:
      warn: false

  - name: Restart Chronyd
    service:
      name: chronyd
      state: restarted
